
# Loads default set of integrations. Do not remove.
default_config:

frontend:
  themes: !include_dir_merge_named themes
http:
  server_port: 8123

browser_mod:

logger:
  default: warning
  logs:
    homeassistant.components.cloud: debug
    custom_components.local_mqtt_service: info
    custom_components.smartir: info

homeassistant:
  packages: !include_dir_named packages

lovelace:
  mode: yaml
  resources:
    - url: /local/iha/air-visual-card/air-visual-card.js
      type: module
    - url: /local/iha/atomic-calendar-revive/atomic-calendar-revive.js
      type: module
    - url: /local/iha/bar-card/bar-card.js
      type: module
    - url: /local/iha/button-card/button-card.js
      type: module
    - url: /local/iha/check-button-card/check-button-card.js
      type: module
    - url: /local/iha/config-template-card/config-template-card.js
      type: module
    - url: /local/iha/ha-card-weather-conditions/ha-card-weather-conditions.js
      type: module
    - url: /local/iha/home-assistant-sun-card/home-assistant-sun-card.js
      type: module
    # - url: /local/iha/kiosk-mode/kiosk-mode.js
    #   type: module
    - url: /local/iha/kodi-search-card/kodi-search-card.js
      type: module
    - url: /local/iha/light-entity-card/light-entity-card.js
      type: module
    - url: /local/iha/light-popup-card/light-popup-card.js
      type: module
    - url: /local/iha/lovelace-auto-entities/auto-entities.js
      type: module
    - url: /local/iha/lovelace-card-mod/card-mod.js
      type: module
    - url: /local/iha/lovelace-card-tools/card-tools.js
      type: module
    - url: /local/iha/lovelace-fan-xiaomi/fan-xiaomi.js
      type: module
    - url: /local/iha/lovelace-fold-entity-row/fold-entity-row.js
      type: module
    - url: /local/iha/lovelace-hui-element/hui-element.js
      type: module
    - url: /local/iha/lovelace-layout-card/layout-card.js
      type: module
    - url: /local/iha/lovelace-more-info-card/more-info-card.js
      type: module
    - url: /local/iha/lovelace-slider-entity-row/slider-entity-row.js
      type: module
    - url: /local/iha/lovelace-state-switch/state-switch.js
      type: module
    - url: /local/iha/lovelace-text-input-row/lovelace-text-input-row.js
      type: module
    - url: /local/iha/lovelace-xiaomi-vacuum-card/xiaomi-vacuum-card.js
      type: module
    - url: /local/iha/lovelace-xiaomi-vacuum-map-card/xiaomi-vacuum-map-card.js
      type: module
    - url: /local/iha/meteo-france-weather-card/meteo-france-weather-card.js
      type: module
    - url: /local/iha/MeteoalarmCard/meteoalarm-card.js
      type: module
    - url: /local/iha/mini-graph-card/mini-graph-card-bundle.js
      type: module
    - url: /local/iha/mini-media-player/mini-media-player-bundle.js
      type: module
    - url: /local/iha/person-entity-card/person-entity-card-bundle.js
      type: module
    - url: /local/iha/scheduler-card/scheduler-card.js
      type: module
    - url: /local/iha/search-card/search-card.js
      type: module
    - url: /local/iha/simple-thermostat/simple-thermostat.js
      type: module
    - url: /local/iha/simple-weather-card/simple-weather-card-bundle.js
      type: module
    - url: /local/iha/slider-button-card/slider-button-card.js
      type: module
    - url: /local/iha/swipe-card/swipe-card.js
      type: module
    - url: /local/iha/switch-popup-card/switch-popup-card.js
      type: module
    - url: /local/iha/thermostat-popup-card/thermostat-popup-card.js
      type: module
    - url: /local/iha/upcoming-media-card/upcoming-media-card.js
      type: module
    - url: /local/iha/vacuum-card/vacuum-card.js
      type: module
    # - url: /local/iha/weather-card/weather-card.js
    #   type: module
    - url: /local/iha/colorfulclouds-weather-card/colorfulclouds-weather-card.js
      type: module
    - url: /local/iha/my-cards/my-cards.js
      type: module
    - url: /local/iha/clock-weather-card/clock-weather-card.js
      type: module
    - url: /local/iha/lovelace-thermostat-card/main.js
      type: module
    - url: /local/iha/lovelace-thermostat-dark-card/thermostat-dark-card.js
      type: module
    - url: /local/iha/vertical-stack-in-card/vertical-stack-in-card.js
      type: module
    - url: /local/calendar-card.js?v=3.109.1
      type: module
    - url: /local/custom_icons.js?v=28082021
      type: module
    - url: /local/marked.min.js?v=4.0.12
      type: module
    - url: /local/vanilla-tilt.min.js?v=1.7.2
      type: module
    - url: /local/font.css
      type: module
  dashboards: 
    ui-lovelace:
      mode: yaml
      title: GS
      icon: mdi:tablet-cellphone
      show_in_sidebar: false
      filename: dashboard/mattias/ui-lovelace.yaml
sun:

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

sensor:
  - platform: time_date
    display_options:
      - 'time'
      - 'date'
      - 'date_time'
      - 'date_time_utc'
      - 'date_time_iso'
      - 'time_date'
      - 'time_utc'
      - 'beat'
